name: CI
 
on:
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
      name: "checkout"
    - name: decK ping
      id: decK_ping
      uses: ./
      with:
        command: "ping"
        options: "--konnect-control-plane-name='default' --konnect-token ${{ secrets.KONG_HEADERS }}"
    - name: decK validate
      id: decK_validate
      uses: ./
      with:
        command: "validate"
        options: "--konnect-control-plane-name='default' --konnect-token ${{ secrets.KONG_HEADERS }}" 
        kong_workspaces: "kong"
    - name: decK diff
      id: decK_diff
      uses: ./
      with:
        command: "diff"
        options: "--konnect-control-plane-name='default' --konnect-token ${{ secrets.KONG_HEADERS }}" 
        kong_workspaces: "kong"
